//! Generated IFC4 ADD2 TC1 concrete `IfcTypeObject` entity types.
//! Source: `/mnt/backup/references/ifc-spec/ifc4-add2-tc1/IFC4.exp`.

pub(crate) const IFC4_CONCRETE_TYPE_OBJECTS: &[&str] = &[
    "IFCACTUATORTYPE",
    "IFCAIRTERMINALBOXTYPE",
    "IFCAIRTERMINALTYPE",
    "IFCAIRTOAIRHEATRECOVERYTYPE",
    "IFCALARMTYPE",
    "IFCAUDIOVISUALAPPLIANCETYPE",
    "IFCBEAMTYPE",
    "IFCBOILERTYPE",
    "IFCBUILDINGELEMENTPARTTYPE",
    "IFCBUILDINGELEMENTPROXYTYPE",
    "IFCBURNERTYPE",
    "IFCCABLECARRIERFITTINGTYPE",
    "IFCCABLECARRIERSEGMENTTYPE",
    "IFCCABLEFITTINGTYPE",
    "IFCCABLESEGMENTTYPE",
    "IFCCHILLERTYPE",
    "IFCCHIMNEYTYPE",
    "IFCCIVILELEMENTTYPE",
    "IFCCOILTYPE",
    "IFCCOLUMNTYPE",
    "IFCCOMMUNICATIONSAPPLIANCETYPE",
    "IFCCOMPRESSORTYPE",
    "IFCCONDENSERTYPE",
    "IFCCONSTRUCTIONEQUIPMENTRESOURCETYPE",
    "IFCCONSTRUCTIONMATERIALRESOURCETYPE",
    "IFCCONSTRUCTIONPRODUCTRESOURCETYPE",
    "IFCCONTROLLERTYPE",
    "IFCCOOLEDBEAMTYPE",
    "IFCCOOLINGTOWERTYPE",
    "IFCCOVERINGTYPE",
    "IFCCREWRESOURCETYPE",
    "IFCCURTAINWALLTYPE",
    "IFCDAMPERTYPE",
    "IFCDISCRETEACCESSORYTYPE",
    "IFCDISTRIBUTIONCHAMBERELEMENTTYPE",
    "IFCDISTRIBUTIONELEMENTTYPE",
    "IFCDOORSTYLE",
    "IFCDOORTYPE",
    "IFCDUCTFITTINGTYPE",
    "IFCDUCTSEGMENTTYPE",
    "IFCDUCTSILENCERTYPE",
    "IFCELECTRICAPPLIANCETYPE",
    "IFCELECTRICDISTRIBUTIONBOARDTYPE",
    "IFCELECTRICFLOWSTORAGEDEVICETYPE",
    "IFCELECTRICGENERATORTYPE",
    "IFCELECTRICMOTORTYPE",
    "IFCELECTRICTIMECONTROLTYPE",
    "IFCELEMENTASSEMBLYTYPE",
    "IFCENGINETYPE",
    "IFCEVAPORATIVECOOLERTYPE",
    "IFCEVAPORATORTYPE",
    "IFCEVENTTYPE",
    "IFCFANTYPE",
    "IFCFASTENERTYPE",
    "IFCFILTERTYPE",
    "IFCFIRESUPPRESSIONTERMINALTYPE",
    "IFCFLOWINSTRUMENTTYPE",
    "IFCFLOWMETERTYPE",
    "IFCFOOTINGTYPE",
    "IFCFURNISHINGELEMENTTYPE",
    "IFCFURNITURETYPE",
    "IFCGEOGRAPHICELEMENTTYPE",
    "IFCHEATEXCHANGERTYPE",
    "IFCHUMIDIFIERTYPE",
    "IFCINTERCEPTORTYPE",
    "IFCJUNCTIONBOXTYPE",
    "IFCLABORRESOURCETYPE",
    "IFCLAMPTYPE",
    "IFCLIGHTFIXTURETYPE",
    "IFCMECHANICALFASTENERTYPE",
    "IFCMEDICALDEVICETYPE",
    "IFCMEMBERTYPE",
    "IFCMOTORCONNECTIONTYPE",
    "IFCOUTLETTYPE",
    "IFCPILETYPE",
    "IFCPIPEFITTINGTYPE",
    "IFCPIPESEGMENTTYPE",
    "IFCPLATETYPE",
    "IFCPROCEDURETYPE",
    "IFCPROTECTIVEDEVICETRIPPINGUNITTYPE",
    "IFCPROTECTIVEDEVICETYPE",
    "IFCPUMPTYPE",
    "IFCRAILINGTYPE",
    "IFCRAMPFLIGHTTYPE",
    "IFCRAMPTYPE",
    "IFCREINFORCINGBARTYPE",
    "IFCREINFORCINGMESHTYPE",
    "IFCROOFTYPE",
    "IFCSANITARYTERMINALTYPE",
    "IFCSENSORTYPE",
    "IFCSHADINGDEVICETYPE",
    "IFCSLABTYPE",
    "IFCSOLARDEVICETYPE",
    "IFCSPACEHEATERTYPE",
    "IFCSPACETYPE",
    "IFCSPATIALZONETYPE",
    "IFCSTACKTERMINALTYPE",
    "IFCSTAIRFLIGHTTYPE",
    "IFCSTAIRTYPE",
    "IFCSUBCONTRACTRESOURCETYPE",
    "IFCSWITCHINGDEVICETYPE",
    "IFCSYSTEMFURNITUREELEMENTTYPE",
    "IFCTANKTYPE",
    "IFCTASKTYPE",
    "IFCTENDONANCHORTYPE",
    "IFCTENDONTYPE",
    "IFCTRANSFORMERTYPE",
    "IFCTRANSPORTELEMENTTYPE",
    "IFCTUBEBUNDLETYPE",
    "IFCTYPEOBJECT",
    "IFCTYPEPRODUCT",
    "IFCUNITARYCONTROLELEMENTTYPE",
    "IFCUNITARYEQUIPMENTTYPE",
    "IFCVALVETYPE",
    "IFCVIBRATIONISOLATORTYPE",
    "IFCWALLTYPE",
    "IFCWASTETERMINALTYPE",
    "IFCWINDOWSTYLE",
    "IFCWINDOWTYPE",
];

pub(crate) fn is_concrete_type_object(name: &str) -> bool {
    let canonical = name.to_ascii_uppercase();
    IFC4_CONCRETE_TYPE_OBJECTS
        .binary_search(&canonical.as_str())
        .is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_inventory_is_sorted_unique_and_keeps_non_type_suffixes() {
        assert_eq!(IFC4_CONCRETE_TYPE_OBJECTS.len(), 119);
        assert!(is_concrete_type_object("IFCTYPEOBJECT"));
        assert!(is_concrete_type_object("IfcWallType"));
        assert!(IFC4_CONCRETE_TYPE_OBJECTS
            .windows(2)
            .all(|pair| pair[0] < pair[1]));
        for name in ["IFCDOORSTYLE", "IFCTYPEPRODUCT", "IFCWINDOWSTYLE"] {
            assert!(is_concrete_type_object(name));
        }
        assert!(!is_concrete_type_object("IFCRELDEFINESBYTYPE"));
    }
}
